FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine3.10 AS publish
WORKDIR /src

COPY . ./
RUN dotnet restore

WORKDIR /src
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine3.10 AS runtime

WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Kryptoteket.Bot.dll"]
